# Generated by Django 4.0.6 on 2022-07-31 21:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='blood_test_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('file_ext', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RenalFunctionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urea', models.CharField(blank=True, max_length=50, null=True, verbose_name='Urea')),
                ('creatinine', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creatnine')),
                ('sodium', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sodium')),
                ('potassium', models.CharField(blank=True, max_length=50, null=True, verbose_name='Potassium')),
                ('chloride', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chloride')),
                ('test_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_input.samplefile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiverFunctionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Albumin')),
                ('total_bilirubin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Bilirubin')),
                ('conjugate_bilirubin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conjugate Bilirubin')),
                ('alanine_aminotransferase', models.CharField(blank=True, max_length=50, null=True, verbose_name='alanine Aminotransferase')),
                ('alkaline_phosphate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alkaline Phosphate')),
                ('test_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_input.samplefile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemoglobin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hemoglobin')),
                ('white_cell_count', models.CharField(blank=True, max_length=50, null=True, verbose_name='White Cell Count')),
                ('sodium', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sodium')),
                ('potassium', models.CharField(blank=True, max_length=50, null=True, verbose_name='Potassium')),
                ('urea', models.CharField(blank=True, max_length=50, null=True, verbose_name='Urea')),
                ('platelet_count', models.CharField(blank=True, max_length=50, null=True, verbose_name='Platelet')),
                ('amylase', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amylase')),
                ('test_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_input.samplefile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
