# Generated by Django 4.0.6 on 2022-07-24 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blod_pressure', models.CharField(blank=True, max_length=100, null=True)),
                ('blod_type', models.CharField(blank=True, max_length=100, null=True)),
                ('blod_rhd', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_test_file', models.FileField(upload_to='blood_test_files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
