# Generated by Django 4.0.6 on 2022-08-01 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodtestresult',
            options={'verbose_name_plural': 'Blood Test Results'},
        ),
        migrations.AlterModelOptions(
            name='liverfunctiontestresult',
            options={'verbose_name_plural': 'Liver Function Test Results'},
        ),
        migrations.AlterModelOptions(
            name='renalfunctionresult',
            options={'verbose_name_plural': 'Renal Function Results'},
        ),
        migrations.AlterField(
            model_name='samplefile',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='test_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
