# Generated by Django 4.0.6 on 2022-07-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0002_bloodtestinfo_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodtestinfo',
            old_name='blod_pressure',
            new_name='blood_pressure',
        ),
        migrations.RenameField(
            model_name='bloodtestinfo',
            old_name='blod_rhd',
            new_name='blood_rhd',
        ),
        migrations.RenameField(
            model_name='bloodtestinfo',
            old_name='blod_type',
            new_name='blood_type',
        ),
        migrations.RemoveField(
            model_name='bloodtestinfo',
            name='blood_test_file',
        ),
        migrations.AddField(
            model_name='bloodtestinfo',
            name='m_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
