# Generated by Django 4.0.6 on 2022-07-25 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0003_rename_blod_pressure_bloodtestinfo_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtestinfo',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtestinfofile',
            name='blood_test_file',
            field=models.FileField(blank=True, null=True, upload_to='blood_test_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
