# Generated by Django 4.0.6 on 2022-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_rename_length_parameter_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='date_awarded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='measure_instrument',
            field=models.CharField(blank=True, choices=[('metric', 'Metric'), ('imperial', 'Imperial'), ('custom', 'Custom')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
