# Generated by Django 4.0.6 on 2022-07-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_alter_parameter_date_awarded_alter_parameter_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
