# Generated by Django 4.0.6 on 2022-07-28 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_alter_parameter_height_alter_parameter_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='battery_life',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='devices',
            name='connection_status',
            field=models.CharField(blank=True, choices=[('connected', 'Connected'), ('not_connected', 'Not Connected')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='date_awarded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='thumbnail',
            field=models.ImageField(upload_to='device'),
        ),
    ]
