# Generated by Django 4.0.6 on 2022-07-28 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0005_alter_devices_battery_life_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'Devices'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='total_points',
        ),
        migrations.AddField(
            model_name='device',
            name='awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='battery_life',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='device',
            name='connection_status',
            field=models.CharField(choices=[('success', 'Connected'), ('danger', 'Not Connected')], default='danger', max_length=30),
        ),
        migrations.AddField(
            model_name='device',
            name='date_awarded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='reward_point',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='device',
            name='thumbnail',
            field=models.ImageField(default='f', upload_to='device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apps',
            name='connection_status',
            field=models.CharField(choices=[('success', 'Connected'), ('danger', 'Not Connected')], max_length=30),
        ),
        migrations.DeleteModel(
            name='App',
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
