# Generated by Django 4.0.6 on 2022-07-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0007_rename_apps_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='thumbnail',
            field=models.ImageField(upload_to='app'),
        ),
    ]
