# Generated by Django 4.0.6 on 2022-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0008_alter_app_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='connection_status',
            field=models.CharField(choices=[('success', 'Connected'), ('danger', 'Not Connected')], default='danger', max_length=30),
        ),
    ]
