# Generated by Django 4.0.6 on 2022-07-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0009_alter_app_connection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='date_awarded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
