# Generated by Django 4.0.6 on 2022-07-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward', '0010_alter_app_date_awarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='reward_points',
            new_name='reward_point',
        ),
        migrations.AddField(
            model_name='reward',
            name='date_awarded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='title',
            field=models.CharField(default='q', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
