# Generated by Django 4.0.6 on 2022-07-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0011_rename_reward_points_reward_reward_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
