# Generated by Django 4.0.6 on 2022-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0012_app_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_name',
            field=models.CharField(choices=[('google', 'Google Fit'), ('samsung', 'Samsung Health'), ('apple', 'Apple Health'), ('garmin', 'Garmin Connect'), ('xiaomi', 'Xiaomi Mi Fit')], max_length=200),
        ),
    ]
